import { ShopInterface } from './shopinterface';

export const SHOPDATA:ShopInterface[] = [{
        id: 1,
        name: "Mechanical operation",
        price: 1000,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..", 
        property_one: "Equipped with a roof only",
        property_two: "Heatable and coolable",
        property_three: "Self-propelled manual control",
	},
	{
        id: 2,
        name: "Controlled operation",
        price: 8634,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..", 
        property_one: "Self-propelled manual control",
        property_two: "Self-propelled remote-controlled",
        property_three: "Controlled operation",
	},
	{
        id: 3,
        name: "Fully covered",
        price: 4444,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..", 
        property_one: "Heatable and coolable",
        property_two: "Self-propelled remote-controlled",
        property_three: "Equipped with a roof only",
	},
	{
        id: 4,
        name: "Time-controlled operation",
        price: 4359,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..", 
        property_one: "Time-controlled operation",
        property_two: "Equipped with a parking assistance radar",
        property_three: "Controlled operation",
	},
	{
        id: 5,
        name: "Mains-powered",
        price: 6546,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..", 
        property_one: "Equipped with a parking assistance radar",
        property_two: "Self-propelled remote-controlled",
        property_three: "Time-controlled operation",
	},
	]
